version: '3.7'

services:

  database-checkout:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: parking
    container_name: db-parking
    ports:
      - 5432:5432